### ISSUE TITLE
Pretrained Model for DeepLabv2

### ISSUE THREAD

**Issue by zkkkkkkkkkkx** [brdav/cma#1]
Hi! Thanks a lot for your great contribution. I find some trouble in downloading the pre-trained model through 'https://data.vision.ee.ethz.ch/brdavid/coma/deeplabv2_cityscapes.pth'. I am wondering if this link is right. Thanks again!

**Comment by brdav** [comment]
Hello, sorry this link was indeed wrong, it should be correct now. Let me know if there are still any issues!
