### ISSUE TITLE
loss=Nan

### ISSUE THREAD

**Issue by smalltoyfox** [brdav/cma#2]
Thank you very much for your excellent open-source project, but during my training of your project, I found that it was normal for loss to exist as nan at the beginning?

**Comment by brdav** [comment]
Nan in the loss or the gradients? Have you tried training without mixed precision?

**Comment by smalltoyfox** [comment]
Nan in the loss,and I'm just trying to use the training command you provided on GitHub. And the final test result on ACDC was only 64.24

**Comment by smalltoyfox** [comment]
Thank you for your reply. Nan in the loss,and I'm just trying to use the training command you provided on GitHub. And the final test result on ACDC was only 64.24.

**Comment by smalltoyfox** [comment]
Thank you for your reply. Nan in the loss,and I'm just trying to use the training command you provided on GitHub. And the final test result on ACDC(segformer) was only 64.24.

**Comment by smalltoyfox** [comment]
Thank you for your reply. Nan in the loss,and I'm just trying to use the training command you provided on GitHub. but Maybe I accidentally modified some code, let me check it.

**Comment by smalltoyfox** [comment]
![loss](https://github.com/brdav/cma/assets/125901934/7b9213ce-8e87-43ec-8301-d4cfc9867001)
just like this, Is this normal?

**Comment by brdav** [comment]
I don't think I've seen this, does it lead to unstable training, i.e., does the training fail? My suggestion would be to try to identify the instability by setting the Trainer argument `detect_anomaly=True` or as a workaround to try full precision training.

**Comment by smalltoyfox** [comment]
Okay, thank you for your answer. The training did not fail, but there is some difference between the results and the values in the paper. The result of testing the segformer on ACDC was 66.2%. I will try detect_anomaly=True out later. Thank you again for your reply.

**Comment by smalltoyfox** [comment]
May I also ask if it is convenient to disclose the training parameters at that time, as there is a slight discrepancy between the results of my reproduced Segformer on ACDC and the results on the ACDC dataset in the article?
