### ISSUE TITLE
test miou

### ISSUE THREAD

**Issue by smalltoyfox** [brdav/cma#4]
Hello author, What options should be selected when testing on the ACDC dataset
![image](https://github.com/user-attachments/assets/7bb865be-f211-41d0-9f03-45677bcdf880)

**Comment by brdav** [comment]
Under "task" you can select which subset of the test set you want to evaluate on. For the main experiments of the CMA paper, we evaluated on "all adverse". 
Under "data used for training" you should unselect "labels", but select "normal-condition images" and potentially "external data" --> Cityscapes
